<a href="https://colab.research.google.com/github/OviRata/Machine-Learning/blob/main/Linear_Regression_on_Wine_Quality_DataSet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler 
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (20.0, 10.0)

In [2]:
!mkdir data && curl -o data/winequality-red.csv -LJO https://github.com/dianaartiom/machine_learning_with_python/raw/main/lesson05/notebooks/data/winequality-red.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 84199  100 84199    0     0   261k      0 --:--:-- --:--:-- --:--:--  261k


In [3]:
data = pd.read_csv('data/winequality-red.csv', sep=';')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
data.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [5]:
# Collecting X and Y
y = data['quality'].values
x = data.drop(['quality'], axis=1).values

Check for NaN values, and normalize the data.

In [6]:
means=[];
for i in range(len(x[0]) ):
  means.append( x.mean(axis=1) );

for i in range( len(x) ):
  for j in range(len(x[i] ) ):
    if pd.isna(x[i][j]):
      x[i][j]=means[j];



mm_scaler = MinMaxScaler();
x = mm_scaler.fit_transform(x);
y = mm_scaler.fit_transform(y.reshape(-1,1));
print(x);
print(y);

[[0.24778761 0.39726027 0.         ... 0.60629921 0.13772455 0.15384615]
 [0.28318584 0.52054795 0.         ... 0.36220472 0.20958084 0.21538462]
 [0.28318584 0.43835616 0.04       ... 0.40944882 0.19161677 0.21538462]
 ...
 [0.15044248 0.26712329 0.13       ... 0.53543307 0.25149701 0.4       ]
 [0.11504425 0.35958904 0.12       ... 0.65354331 0.22754491 0.27692308]
 [0.12389381 0.13013699 0.47       ... 0.51181102 0.19760479 0.4       ]]
[[0.4]
 [0.4]
 [0.4]
 ...
 [0.6]
 [0.4]
 [0.6]]


Separate the training and test datasets.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Instantiate the LinearRegression model from the sklearn.linear_model. Use *fit* to train the model.

In [8]:
from sklearn.linear_model import LinearRegression

regr = LinearRegression()
regr.fit(X_train, y_train)

LinearRegression()

Predict the results with the trained linear regression model, then, calculate the accuracy of the model.

In [13]:
from sklearn.metrics import mean_squared_error

y_pred_train = regr.predict(X_train);

print(f" The accuracy of the model on training data is: {regr.score( X_train, y_train )*100}%" )

print(f"The mean squared error of the model in training data is: {mean_squared_error(y_train, y_pred_train)}")

 The accuracy of the model on training data is: 34.79926193529861%
The mean squared error of the model in training data is: 0.016967646292559615


In [14]:
y_pred_test =regr.predict(X_test);
print(f" The accuracy of the model on test data is: {regr.score( X_test, y_test )*100}%" )

print(f"The mean squared error of the model on test data is: {mean_squared_error(y_test, y_pred_test)}")

 The accuracy of the model on test data is: 40.31803412796216%
The mean squared error of the model on test data is: 0.015601005758558214
